"""adding polygon_json

Revision ID: 065d6452f12a
Revises: b2c272338e4e
Create Date: 2025-08-01 19:17:23.298131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065d6452f12a'
down_revision = 'b2c272338e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polygon_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polygon_json')
    # ### end Alembic commands ###
