"""empty message

Revision ID: 35d52d8e4431
Revises: cf3a28c8f107
Create Date: 2025-07-26 08:03:24.744946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d52d8e4431'
down_revision = 'cf3a28c8f107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('processing_status', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('processing_status')
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
