"""add created_at for PolygonFeature model

Revision ID: 80e62f33ccec
Revises: ccf2dcea1133
Create Date: 2025-07-27 05:32:13.554287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e62f33ccec'
down_revision = 'ccf2dcea1133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polygon_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polygon_features', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
