"""update null for center lat lon

Revision ID: b2c272338e4e
Revises: 80e62f33ccec
Create Date: 2025-07-27 06:20:32.692039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c272338e4e'
down_revision = '80e62f33ccec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('polygon_features', schema=None) as batch_op:
        batch_op.alter_column('damage_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('class_label',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polygon_features', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('coordinates',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('class_label',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('damage_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
