"""Allow null for center coords

Revision ID: ccf2dcea1133
Revises: 35d52d8e4431
Create Date: 2025-07-26 15:08:00.180604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf2dcea1133'
down_revision = '35d52d8e4431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.alter_column('center_lat',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('center_lon',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.alter_column('center_lon',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('center_lat',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
